name: Build & Release

on:
  push:
    tags:
      - '*'   # qualsevol tag

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Build CliPG
        working-directory: ./CliPG
        run: cargo build --release

      - name: Build SerPG
        working-directory: ./SerPG
        run: cargo build --release

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            CliPG/target/release/*
            SerPG/target/release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
