name: Build & Release

on:
  push:
    tags:
      - '*'   # qualsevol tag

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build CliPG
        working-directory: ./CliPG
        run: cargo build --release

      - name: Build SerPG
        working-directory: ./SerPG
        run: cargo build --release

      - name: Create GitHub Release and upload executables
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./CliPG/target/release/CliPG
            ./SerPG/target/release/SerPG
